/***************************************************************************//**
* \file CAP_MODEL_tflm_y_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the CAP_MODEL model in int8x8 representation.
* Date: 2024-09-30 16:22:29.898516
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef CAP_MODEL_TFLM_Y_DATA_INT8X8_H
#define CAP_MODEL_TFLM_Y_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t CAP_MODEL_y_data_bin[];
#define CAP_MODEL_Y_DATA_BIN_LEN (2000)

#endif // CAP_MODEL_TFLM_Y_DATA_INT8X8_H

