/***************************************************************************//**
* \file MODEL_tflm_y_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the MODEL model in float representation.
* Date: 2024-10-09 17:36:34.571421
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MODEL_TFLM_Y_DATA_FLOAT_H
#define MODEL_TFLM_Y_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t MODEL_y_data_bin[];
#define MODEL_Y_DATA_BIN_LEN (8000)

#endif // MODEL_TFLM_Y_DATA_FLOAT_H

