/***************************************************************************//**
* \file MODEL_tflm_x_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MODEL model in int8x8 representation.
* Date: 2024-10-09 17:36:34.644423
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MODEL_TFLM_X_DATA_INT8X8_H
#define MODEL_TFLM_X_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t MODEL_x_data_bin[];
#define MODEL_X_DATA_BIN_LEN (150016)

#endif // MODEL_TFLM_X_DATA_INT8X8_H

