/***************************************************************************//**
* \file CAP_MODEL_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the CAP_MODEL model in float representation.
* Date: 2024-10-02 06:56:31.507016
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef CAP_MODEL_TFLM_X_DATA_FLOAT_H
#define CAP_MODEL_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t CAP_MODEL_x_data_bin[];
#define CAP_MODEL_X_DATA_BIN_LEN (288016)

#endif // CAP_MODEL_TFLM_X_DATA_FLOAT_H

