/***************************************************************************//**
* \file MODEL_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MODEL model data.
* Date: 2024-10-09 17:36:34.274753
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MODEL_TFLM_MODEL_INT8X8_H
#define MODEL_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MODEL_model_bin[];
#else
extern uint8_t MODEL_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MODEL_MODEL_BIN_LEN (12560u)
#define MODEL_ARENA_SIZE (16384u)

#endif // MODEL_TFLM_MODEL_INT8X8_H

