/***************************************************************************//**
* \file MODEL_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MODEL model in float representation.
* Date: 2024-09-20 13:44:22.423495
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MODEL_TFLM_X_DATA_FLOAT_H
#define MODEL_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t MODEL_x_data_bin[];
#define MODEL_X_DATA_BIN_LEN (600016)

#endif // MODEL_TFLM_X_DATA_FLOAT_H

