name: PR Approved

on:
  pull_request_review:
    types:
      - submitted

jobs:
  start_pipeline:
    if: github.event.review.state == 'approved'
    uses: 'Infineon/deepcraft-starter-models/.github/workflows/start_pipeline.yml@ee9c56dce718e5d30f35e60a3b1e0ba030b00632'
