name: PR Updated

on:
  pull_request_target:
    branches:
      - main

jobs:
  start_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Start Pipeline
        env:
          STARTER_MODELS_PIPELINE_TOKEN: ${{ secrets.STARTER_MODELS_PIPELINE_TOKEN }}
          PR_HEAD: ${{ toJson(github.event.pull_request.head) }}
        run: |
          python -m pip install requests
          python start_pipeline.py
