name: PR Updated

on:
  pull_request_target:
    branches:
      - main

jobs:
  start_pipeline:
    uses: 'Infineon/deepcraft-starter-models/.github/workflows/start_pipeline.yml@22c9c7a7e5ff1ad37dea4635cd8c6c2843c03ce5'
